--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/OiranCage/StrictForm
build-by-default: true
branches:
- main
projects:
  StrictForm:
    path: ""
    model: virion
    type: library
...
